config/routes.rb
Cristiancastillo::Application.routes.draw do 
  devise_for :users, :as  => :cuentas

  resources :tags do
    get 'autocomplete_for_tag_name', :on => :collection 
  end
  
  resources :posts do |variable|
    resources :comentarios
    resources :figuras
  end
  
  resources :contactos
  
  resources :users do
    resources :posts
    resources :categorias
  end
  
  root :to => "posts#index"
  

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  attr_accessible :nombre, :email, :texto
  belongs_to :user
  validates_presence_of :nombre, :texto
  validates_format_of :email, :with => Ccp::EmailAddress
  
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  before_filter :autorizado?, :except => [:new, :create, :show]
  
  def index
    @contactos = Contacto.all
  end
  
  def show
    @contacto = Contacto.find(params[:id])
  end
  
  def new
    @contacto = Contacto.new
    if user_signed_in?
      @contacto.email = current_user.email
      @contacto.nombre = current_user.nombre
    end
  end
  
  def create
    @contacto = Contacto.new(params[:contacto])
    @contacto.user = current_user if user_signed_in?
    if @contacto.save
      flash[:notice] = "Se registró correctamente contacto."
      redirect_to @contacto
    else
      render :action => 'new'
    end
  end
  
  def edit
    @contacto = Contacto.find(params[:id])
  end
  
  def update
    @contacto = Contacto.find(params[:id])
    if @contacto.update_attributes(params[:contacto])
      flash[:notice] = "Se actualizó correctamente contacto."
      redirect_to @contacto
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @contacto = Contacto.find(params[:id])
    @contacto.destroy
    flash[:notice] = "Successfully destroyed contacto."
    redirect_to contactos_url
  end
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/views/contactos/_form.html.haml
- semantic_form_for @contacto do |form|
  = form.error_messages
  - form.inputs do
    = form.input :nombre
    = form.input :email
    = form.input :texto
  - form.buttons do
    = form.commit_button "Submit"

app/views/contactos/edit.html.haml
- title "Edit Contacto"

= render :partial => 'form'

%p
  = link_to "Show", contacto_path(@contacto)
  |
  = link_to "View All", contactos_path

app/views/contactos/index.html.haml
- title "Contactos"

%table
  %tr
    %th Nombre
    %th Email
    %th Texto
    %th User
  - for contacto in @contactos
    %tr
      %td= contacto.nombre
      %td= contacto.email
      %td= contacto.texto
      %td= contacto.user_id
      %td= link_to 'Show', contacto
      %td= link_to 'Edit', edit_contacto_path(contacto)
      %td= link_to 'Destroy', contacto, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Contacto", new_contacto_path

app/views/contactos/new.html.haml
- title "Contáctenos"

= render :partial => 'form'

%p= link_to "Back to List", contactos_path

app/views/contactos/show.html.haml
- title "Contacto"

%p
  %strong Nombre:
  =h @contacto.nombre
%p
  %strong Email:
  =h @contacto.email
%p
  %strong Texto:
  =h @contacto.texto
%p
  %strong User:
  =h @contacto.user_id

%p
  = link_to "Edit", edit_contacto_path(@contacto)
  |
  = link_to "Destroy", @contacto, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", contactos_path