config/routes.rb
Cristiancastillo::Application.routes.draw do 
  devise_for :users, :as  => :cuentas

  resources :tags do
    get 'autocomplete_for_tag_name', :on => :collection 
  end
  
  resources :posts do |variable|
    resources :comentarios
    resources :figuras
  end
  
  resources :contactos
  
  resources :users do
    resources :posts
    resources :categorias
  end
  
  root :to => "posts#index"
  

end

app/models/figura.rb
class Figura < ActiveRecord::Base
  validates_presence_of :nombre
  belongs_to :user
  belongs_to :post
  has_attached_file :img, 
                    :styles => {  :extra  => "800x600>",
                                  :large => "405x302>",
                                  :medium => "197x148#",
                                  :thumb => "77x57#" }  
  
  def to_s
    nombre
  end

end

app/controllers/figuras_controller.rb
class FigurasController < ApplicationController
  before_filter :get_post
  before_filter :autorizado?, :except => :show
  
  def index
    @figuras = @post.figuras
  end
  
  def show
    @figura = Figura.find(params[:id])
  end
  
  def new
    @figura = Figura.new
  end
  
  def create
    @figura = Figura.new(params[:figura])
    @figura.user = current_user
    @figura.post = @post
    if @figura.save
      flash[:notice] = "Successfully created figura."
      redirect_to [@post,@figura]
    else
      render :action => 'new'
    end
  end
  
  def edit
    @figura = Figura.find(params[:id])
  end
  
  def update
    @figura = Figura.find(params[:id])
    if @figura.update_attributes(params[:figura])
      flash[:notice] = "Successfully updated figura."
      redirect_to [@post,@figura]
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @figura = Figura.find(params[:id])
    @figura.destroy
    flash[:notice] = "Successfully destroyed figura."
    redirect_to post_figuras_url(@documento)
  end

  private
    def get_post
      @post = Post.find(params[:post_id])
    end

  
end

app/views/figuras/_figura.html.haml
.figure{:id=>"figura_#{figura}"}
  %p.caption= "#{figura.descripcion}"
  %p.art
    = image_tag(figura.url, :alt => figura )

app/views/figuras/_form.html.haml
- form_for [@post, @figura], :html => { :multipart => true } do |f|
  = f.error_messages

  %p
    = f.label :img, "Imagen o foto, JPG, GIF, PNG"
    %br
    = f.file_field :img

  %p
    = f.label :nombre
    %br
    =f.text_field :nombre
  %p
    = f.label :descripcion
    %br
    = f.text_area :descripcion, :cols=>30, :rows=>5
  %p
    = f.submit "Registrar"

app/views/figuras/edit.html.haml
- title "Edit Figura"

= render :partial => 'form'

%p
  = link_to "Show", post_figura_path(@post, @figura)
  |
  = link_to "View All", post_figuras_path(@post)

app/views/figuras/index.html.haml
%h1
  = "Figuras de #{@documento}"
%p= link_to "#{image_tag('icons/add.png')} Nueva Figura", new_post_figura_path(@post)

- if @figuras.size > 0

  %table
    %tr
      %th Documento
      %th Código
      %th Imagen
      %th Nombre
      %th Descripción
        
    - for figura in @figuras
      %tr
        %td= link_to figura.post, figura.post
        %td= "figura_#{figura.id}"
        %td= image_tag figura.img.url(:thumb)
        %td= figura.nombre
        %td= figura.descripcion
        %td= link_to 'Show', [@post,figura]
        %td= link_to 'Edit', edit_post_figura_path(@post,figura)
        %td= link_to 'Destroy', [@post,figura], :confirm => 'Are you sure?', :method => :delete

- else

  %p 
    Aún no ha subido figuras. 
    Para hacerlo, haga clic en 
    = link_to "Nueva Figura", new_post_figura_path(@post)
    %br
    Luego, puede insertar la figura simplemente insertando el texto:
    %br
    %strong
      figura_XX
    directamente en el contenido

app/views/figuras/new.html.haml
- title "New Figura"

= render :partial => 'form'

%p= link_to "<< Regresar", post_figuras_path(@post)

app/views/figuras/show.html.haml
- title @figura

%p
  %strong Dentro de:
  =h @figura.post
%p
  = image_tag @figura.img.url
%p
  %strong Nombre:
  =h @figura.nombre
%p
  %strong Descripcion:
  =h @figura.descripcion

- if user_signed_in?
  %p
    = link_to "Edit", edit_post_figura_path(@post,@figura)
    |
    = link_to "Destroy",[@post,@figura], :confirm => 'Are you sure?', :method => :delete
    |
    = link_to "View All", post_figuras_path(@post)
    |
    = link_to "Nueva Figura", new_post_figura_path(@post)