config/routes.rb
Cristiancastillo::Application.routes.draw do 
  devise_for :users, :as  => :cuentas

  resources :tags do
    get 'autocomplete_for_tag_name', :on => :collection 
  end
  
  resources :posts do |variable|
    resources :comentarios
    resources :figuras
  end
  
  resources :contactos
  
  resources :users do
    resources :posts
    resources :categorias
  end
  
  root :to => "posts#index"
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable
  attr_accessible :titulo, :resumen, :texto, :categoria_id, :tag_list
  belongs_to :user
  belongs_to :categoria
  has_many :comentarios
  has_many :figuras
  validates_presence_of :titulo, :texto

  versioned
  
  scope :libres, where("categoria_id <> 2")

  def self.per_page
    15
  end
    
  def to_s
    titulo
  end

  def to_param
    "#{id}-#{to_s.parameterize}"
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :iniciar
  before_filter :autorizado?, :except => [:show,:index]  
  def index
    page = params[:page]
    page ||= 1 
    @posts = @user.posts.where("categoria_id <> 2").paginate(:page => params[:page], :order=> "created_at desc")
  end
  
  def show
    @post = Post.find(params[:id])
    @post.revert_to(params[:version].to_i) if params[:version]
    c = Comentario.new
    c.post = @post
    if user_signed_in?
      c.user = current_user
      c.email = current_user.email
      c.web = current_user.web
    end
    @comentario = c
    spamify(@comentario)    
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    if @post.save
      flash[:notice] = "Se registró correctamente post."
      redirect_to [@user,@post]
    else
      render :action => 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      flash[:notice] = "Se actualizó correctamente post."
      redirect_to [@user,@post]
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Successfully destroyed post."
    redirect_to user_posts_url(@user)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
  # def to_html(text, ancho = :large)
  #   #procesado del texto.
  #   #existen imágenes
  #   #text = text.pandoku(:markdown => :html)
  #   
  #   #text = (text.blank? ? "" : Maruku.new(text).to_html)
  #   text = text.pandoku(:markdown, :html)
  #   text.gsub!(/figura_([0-9]+)/) do |id|
  #     #begin
  #       f = Figura.find($1.to_i)
  #       render_figura(f, ancho)
  #     #rescue
  #     #  content_tag(:p, "-figura no encontrada-",:class=>:error)
  #     #end
  #   end
  #   text
  # end

  # Format text for display.                                                                    
  def to_html(text, ancho = :large)
    text = sanitize(markdown(text))

    text.gsub!(/figura_([0-9]+)/) do |id|
      #begin
        f = Figura.find($1.to_i)
        render_figura(f, ancho)
      #rescue
      #  content_tag(:p, "-figura no encontrada-",:class=>:error)
      #end
    end
    text
  end

  # Process text with Markdown.                                                                 
  def markdown(text)
    BlueCloth::new(text).to_html
  end

  
  def render_figura(figura, ancho)
    content_tag(:div, 
      [ content_tag(:p, link_to( image_tag(figura.img.url(ancho), :alt => figura, :title=>figura ),  [figura.post,figura], :class=>"box" ), :class => :art),
        content_tag(:p, figura.nombre, :class => :caption),
        content_tag(:p, figura.descripcion, :class => :nota) ].join("\n"),
      :id => figura,
      :class => "figure"
    )
  end
end

app/views/posts/_form.html.haml
- javascript :defaults, 'jquery.autocomplete'
- stylesheet "jquery.autocomplete"

- form_for [@user,@post] do |f|
  = f.error_messages
  %p 
    = f.label :titulo
    %br
    = f.text_field :titulo
    %br
    = f.label :resumen
    %br
    = f.text_field :resumen
    %br
    = f.label :texto
    %br
    = f.text_area :texto, :cols=>70
    %br
    = f.label :categoria_id
    %br
    = f.collection_select(:categoria_id, Categoria.find(:all,:order=>"nombre desc"), :id, :nombre, {:prompt => "-sin clase-"})
    %br
    = f.label :tags
    %br
    = f.text_field :tag_list, :class => 'autocomplete', 'autocomplete_url'=>autocomplete_for_tag_name_tags_path
    %br
    = f.submit "Registrar"

app/views/posts/_leyenda.html.haml
%p{:class=>"leyenda"}
  %em{:class=>"gris"} Del:
  = l post.created_at, :format => "%d %B %Y"
  %em{:class=>"gris"} por:
  = post.user
  %em{:class=>"gris"} dentro de:
  /= post.categoria

app/views/posts/_post.html.haml
.entrada
  %h2= link_to h( post.titulo), [@user,post]
  = render :partial => 'posts/leyenda', :locals => {:post => post} 
  
  %p{:class=>"resumen"}
    = link_to h(post.resumen), [@user,post]
  
  %p
    = truncate_words post.texto
    = link_to "Seguir leyendo...[+]", [@user,post]

app/views/posts/edit.html.haml
- title "Edit Post"

= render :partial => 'form'
%p
  = link_to "Show", [@user,@post]
  |
  = link_to "View All", user_posts_path(@user)

%h3 Figuras
%iframe{:src=>post_figuras_path(@post), :width=>"100%", :height=>"300px"}

app/views/posts/index.html.haml
- title ""
- description
= will_paginate @posts
= render :partial => 'post', :collection => @posts, :spacer_template => "layouts/divisor"

app/views/posts/new.html.haml
- title "New Post"

= render :partial => 'form'

%p= link_to "Back to List", user_posts_path(@user)

app/views/posts/show.html.haml
- title h @post.titulo
- description h @post.resumen

- content_for :head, stylesheet_link_tag('/fancybox/jquery.fancybox-1.2.5.css')
- content_for :head, javascript_include_tag(:defaults)
- content_for :head, javascript_include_tag('/fancybox/jquery.fancybox-1.2.5.js')

= render :partial => 'posts/leyenda', :locals => {:post => @post} 

- if user_signed_in? and current_user.admin
  %p
    %strong V# 
    = @post.version
    |
    = link_to("Versión previa", user_post_path(@user,@post, :version => @post.version - 1)) if @post.version and @post.version > 1
    |
    = link_to("Última versión", user_post_path(@user,@post, :version => nil)) if params[:version]
    |
    = link_to "Editar", edit_user_post_path(@user,@post)
    |
    = link_to "Eliminar", [@user,@post], :confirm => 'Are you sure?', :method => :delete
    |
    = link_to "Ver todas", user_posts_path(@user)
  
.entrada

  %p{:class=>"resumen"}
    = @post.resumen

  = to_html @post.texto
  
  %p= add_this
  
  %p{:class=>"leyenda"}
    %em{:class=>"gris"} Dentro de
    = @post.categoria
    %em{:class=>"gris"} Etiquetado como
    = @post.tag_list

.divisor

.comentarios

  %h3="#{@post.comentarios.count} comentarios"
  = render :partial => "comentarios/comentario", :collection =>  @post.comentarios, :spacer_template => "layouts/divisor"

  .divisor

  %h3 Nuevo comentario
  = nuevo_comentario


:javascript
  $(document).ready(function() { 
    $("a.box").fancybox({ 
      'hideOnContentClick': false,
      'zoomOpacity'			: true,
      'zoomSpeedIn'     : 400, 
      'zoomSpeedOut'    : 400, 
      'overlayShow'			: true,
      'frameWidth'      : 900,
      'frameHeight'     : 500
    });
  }); 