config/routes.rb
Cristiancastillo::Application.routes.draw do 
  devise_for :users, :as  => :cuentas

  resources :tags do
    get 'autocomplete_for_tag_name', :on => :collection 
  end
  
  resources :posts do |variable|
    resources :comentarios
    resources :figuras
  end
  
  resources :contactos
  
  resources :users do
    resources :posts
    resources :categorias
  end
  
  root :to => "posts#index"
  

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title (page_title = "Consultoría en temas de desarrollo WEB y estrategia de TI",
            show_title = true)
    content_for(:head) { 
      content_tag(:title, "#{page_title.to_s} | Cristiancastillo.com")
    }
    @show_title = show_title
    if show_title?
      content_for(:title){ page_title }
    end
  end
  
  def show_title?
    @show_title
  end
  
  def description( d= "Consultoría y desarrollo de aplicaciones WEB, estratégia de negocios WEB, 
    marketing sobre WEB y temas relacionados con tecnologías de información, marketing y redes sociales")
    content_for(:head) {
      tag(:meta, :name => "description" ,:content=>h(d) )
    }
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  
  def lenguetas
    t = ""
    tabs({:always_link => true }) do |tab|
      t << tab.home( "Home", root_path)
      
      Categoria.menu.each do |c|
        t << eval("tab.#{c.nombre.parameterize}(\"#{c.nombre}\", \"#{polymorphic_url([User.first,c])}\")")
      end
      
      t << tab.contacto( "Contacto", new_contacto_path)
    end
    t.html_safe
  end
  
  #entrega las categorías con entradas
  def categorias
    t = ""
    Categoria.all(:order => "nombre", :conditions => "menu is false").each do |c|
      t << content_tag(:li, link_to(c.nombre, [c.user, c]))
    end
    content_tag( :ul, t.html_safe, :id => "categorias")
  end
  
  def add_this
    add_this = <<texto
    <!-- AddThis Button BEGIN -->
      <a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;username=ccastillop">
        <img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/>
      </a>
      <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=ccastillop"></script>
    <!-- AddThis Button END -->
texto
    add_this.html_safe
  end
  
  def truncate_words(text, length = 80, end_string = ' …')
    return if text.nil?
    text = strip_tags text
    words = text.split()
    words[0..(length-1)].join(' ') + (words.length > length ? end_string : '')
  end
  
  def google_analytics
    texto = <<javascript
    
    <script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
    try {
    var pageTracker = _gat._getTracker("UA-12865942-1");
    pageTracker._trackPageview();
    } catch(err) {}</script>
    
javascript
    texto.html_safe
  end
  
    def facebook_like
      fb = <<facebook
      <iframe src="http://www.facebook.com/widgets/like.php?href=#{request.url}"
              scrolling="no" frameborder="0"
              style="border:none; width:170px; height:160px">
      </iframe>

facebook
      fb.html_safe
    end
  
end

app/views/layouts/_divisor.html.haml
.divisor

app/views/layouts/_usuario.html.haml
- if user_signed_in?
  = "Bienvenid@"
  = current_user
  |
  = link_to "Modificar datos", edit_user_path(current_user)
  |
  = link_to "Entradas", user_posts_path(current_user)
  |
  = link_to "Categorías", user_categorias_path(current_user)
  |
  = link_to "Salir", destroy_user_session_path, :confirm => "Cerraré la sesión. ¿Procedo?"
- else
  %p
    = link_to "Iniciar sesión", new_user_session_path
    |
    = link_to "Regístrate", new_user_path

app/views/layouts/application.html.haml
!!! Strict
%html{html_attrs}

  %head
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    %meta( name="google-site-verification" content="uZ_pGNrkkzCJXfSUxTREnnV8UoEm6mZ6XNdjvDQJ-zo" )/
    = stylesheet_link_tag 'application'
    = csrf_meta_tag
    = yield(:head)

  %body
    #header
      .contenido_header
        #logo
          %p="cristian<span class='apa'>Castillo</span>".html_safe
          %p.slogan
            haciendo las cosas fáciles
        #user
          .current_user
            = render :partial => 'layouts/usuario'
          #menu
            /= lenguetas
          .clear
        .clear

    #center
      .contenido
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}"
          
        #izquierda
          - if show_title?
            %h1= yield(:title)

          = yield

        #derecha
          %p
            = image_tag @user.gravatar_url if @user

          %p
            = facebook_like
          %p
            Buscador (Google)

          %p
            Suscribirse

          %p 
            Categorías

          = categorias

          %p 
            Links:
            %ul
              %li= link_to "Blogpuntocom.com", "http://blogpuntocom.com"
              %li= link_to "Z-nexus", "http://z-nexus.com"
              %li= link_to "Casadelima.com", "http://casadelima.com"
              %li= link_to "Casadeplaya.com", "http://casadeplaya.com"
              %li= link_to "Grupo Ruby on Rails Perú", "http://groups.google.com.pe/group/rubyonrailsperu"
              %li= link_to "Página del grupo RoR Perú", "http://rails.pe"
              %li= link_to "Código fuente de este blog", "http://github.com/znexus/blog"

          - if user_signed_in?
            %p= link_to("Nueva entrada", new_user_post_path(current_user))
  
        .clear
      
    #footer
      .contenido
        Desarrollado por 
        = link_to "Yo mismo :)", "http://github.com/znexus/blog"
      = google_analytics

app/views/layouts/figuras.html.haml
!!! Strict
%html{html_attrs}
  
  %head
    %title
      = h(yield(:title) || "Untitled")
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag 'application'
    = yield(:head)
  
  %body
    = yield